CREATE TABLE `y_ztry` (
  `ztrybh` varchar(25) NOT NULL, 
  `xm` varchar(20) NOT NULL,
  `bmch` varchar(20) DEFAULT NULL,
  `xbdm` varchar(20) DEFAULT NULL,
  `mzdm` varchar(20) DEFAULT NULL,
  `csrq` varchar(20) DEFAULT NULL,
  `hjdz` varchar(20) DEFAULT NULL,
  `xzqhdm` varchar(20) DEFAULT NULL,
  `hjdz_dzmc` varchar(20) DEFAULT NULL,
  `xzz_xzqhdm` varchar(20) DEFAULT NULL,
  `xzz_dzmc` varchar(20) DEFAULT NULL,
  `sfzh` varchar(20) DEFAULT NULL,
  `cyzj` varchar(20) DEFAULT NULL,
  `sgxx` varchar(20) DEFAULT NULL,
  `asjbh` varchar(20) DEFAULT NULL,
  `tpsj` varchar(20) DEFAULT NULL,
  `tpfx_jyqk` varchar(20) DEFAULT NULL,
  `tjjbdm` varchar(20) DEFAULT NULL,
  `ztjj` varchar(20) DEFAULT NULL,
  `ztrylxdm` varchar(20) DEFAULT NULL,
  `ladw_gajgjgdm` varchar(20) DEFAULT NULL,
  `zbr_xm` varchar(20) DEFAULT NULL,
  `zbr_lxdh` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ztrybh`),
  KEY `idxztry_1` (`sfzh`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='附件表';
